In [25]:
import torch

In [26]:
x = torch.tensor([5.], requires_grad=True)

In [27]:
y = torch.tensor([6.], requires_grad=True)

In [28]:
x

tensor([5.], requires_grad=True)

In [29]:
y

tensor([6.], requires_grad=True)

In [30]:
z = x**3 - y **2 

In [31]:
z

tensor([89.], grad_fn=<SubBackward0>)

In [32]:
# dy/dx = 3X**2
# dy/dy = -2Y

In [33]:
print(x.grad)

None


In [36]:
z.backward()  # derivative with respect to both X and Y 

In [37]:
x.grad

tensor([75.])

In [38]:
y.grad

tensor([-12.])

In [39]:
w = torch.randn(10, 1, requires_grad=True)

In [43]:
b= torch.randn(1, requires_grad=True)

In [44]:
w

tensor([[ 1.3010],
        [-0.8325],
        [-1.8958],
        [ 0.5898],
        [ 1.0540],
        [-0.9107],
        [ 0.0248],
        [-0.7608],
        [ 0.5802],
        [-0.3091]], requires_grad=True)

In [45]:
b

tensor([-0.0652], requires_grad=True)

In [55]:
i = torch.rand(1,10) # normally X 

In [56]:
i

tensor([[0.6674, 0.3685, 0.1304, 0.5532, 0.0479, 0.1345, 0.4997, 0.6757, 0.9024,
         0.4230]])

In [63]:
output = torch.matmul(i, w) + b

In [64]:
output

tensor([[0.3944]], grad_fn=<AddBackward0>)

In [65]:
loss = 1 - output

In [66]:
loss

tensor([[0.6056]], grad_fn=<RsubBackward1>)

In [67]:
loss.backward()

In [68]:
w.grad

tensor([[-0.6674],
        [-0.3685],
        [-0.1304],
        [-0.5532],
        [-0.0479],
        [-0.1345],
        [-0.4997],
        [-0.6757],
        [-0.9024],
        [-0.4230]])

In [69]:
b.grad

tensor([-1.])

In [70]:
# after first iteration 

In [71]:
with torch.no_grad():
  w = w - 0.01 * w.grad.data

In [72]:
w

tensor([[ 1.3077],
        [-0.8288],
        [-1.8945],
        [ 0.5953],
        [ 1.0545],
        [-0.9094],
        [ 0.0298],
        [-0.7541],
        [ 0.5892],
        [-0.3049]])