In [1]:
import torch
import numpy as np  

In [2]:
sample = [[1,2,3], [4,5,6]]

In [5]:
sample

[[1, 2, 3], [4, 5, 6]]

In [6]:
type(sample)

list

In [9]:
nsample = np.array(sample)

In [10]:
type(nsample)

numpy.ndarray

In [12]:
tsample = torch.tensor(sample)

In [13]:
type(tsample)

torch.Tensor

## A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array

In [14]:
tsample.dtype

torch.int64

In [16]:
np_array = np.random.randn(3,5)

In [17]:
np_array

array([[ 0.05539134,  1.34590352,  0.53753771, -0.95660329, -0.52795612],
       [-0.87751394,  0.590305  , -0.03866599, -2.33966488, -0.32204732],
       [-0.50357214,  1.1531002 , -1.43346504, -0.61648174, -1.40574861]])

In [18]:
torch.from_numpy(np_array)

tensor([[ 0.0554,  1.3459,  0.5375, -0.9566, -0.5280],
        [-0.8775,  0.5903, -0.0387, -2.3397, -0.3220],
        [-0.5036,  1.1531, -1.4335, -0.6165, -1.4057]], dtype=torch.float64)

In [20]:
torch.tensor(np_array)

tensor([[ 0.0554,  1.3459,  0.5375, -0.9566, -0.5280],
        [-0.8775,  0.5903, -0.0387, -2.3397, -0.3220],
        [-0.5036,  1.1531, -1.4335, -0.6165, -1.4057]], dtype=torch.float64)

In [23]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
torch.rand(5)

tensor([0.0799, 0.9417, 0.1142, 0.5619, 0.8731])

In [25]:
tsample.device

device(type='cpu')

In [26]:
tsample

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# tsample.to(device='cuda') # no GP error 

In [33]:
tsample.mul(tsample)  # element wise multiplication 

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [36]:
tsample.shape  # 2 rows 3 columns

torch.Size([2, 3])

In [40]:
torch.matmul(tsample, tsample.T)

tensor([[14, 32],
        [32, 77]])

In [41]:
tsample

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
tsample.sum(axis=1)

tensor([ 6, 15])

In [42]:
tsample.sum(axis=0)

tensor([5, 7, 9])

In [43]:
tsample.min()

tensor(1)

In [49]:
tsample.max()

tensor(6)

In [50]:
st = torch.rand(5)
st

tensor([0.5972, 0.1376, 0.0540, 0.7222, 0.2580])

In [51]:
torch.nn.functional.softmax(st, dim=0)

tensor([0.2464, 0.1556, 0.1431, 0.2792, 0.1755])